spring:
  data:
    mongodb:
      database: "miguel"
      host: "127.0.0.1"
      port: 27017

fluentd:
  tag: "com.milfist.mongo"
  host: "localhost"
  port: 24224

logging:
  level:
    com:
      milfist: TRACE
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
            repository:
              Query: DEBUG
